// This screen displays the detailed view of a tutorial, including video playback, a timestamped timeline, and AI-generated instructions.
import { View, Text, StyleSheet, ScrollView, Pressable, ActivityIndicator } from 'react-native';
import { useState, useEffect } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Video, ResizeMode } from 'expo-av';
import { theme } from '@/src/styles/theme';
import { TutorialsRepository } from '@/api/tutorial.api.client';
import ITutorial from '@/models/ITutorial';

import ProgressBar from '@/src/components/ProgressBar';
import StepItem from '@/src/components/StepItem';

export default function TutorialDetailScreen() {
  const { id } = useLocalSearchParams();
  const router = useRouter();
  
  const [tutorial, setTutorial] = useState<ITutorial | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'timeline' | 'manual'>('timeline');
  const [activeStepIndex, setActiveStepIndex] = useState(0);

  useEffect(() => {
    async function loadTutorial() {
      if (!id) return;
      try {
        const data = await TutorialsRepository.getById(id as string);
        setTutorial(data);
      } catch (e) {
        console.error("Failed to load tutorial", e);
      } finally {
        setLoading(false);
      }
    }
    loadTutorial();
  }, [id]);

  if (loading) return (
    <View style={styles.centered}>
      <ActivityIndicator size="large" color={theme.colors.accentGold} />
      <Text style={{ color: 'white', marginTop: 10 }}>Loading tutorial...</Text>
    </View>
  );

  if (!tutorial) return (
    <View style={styles.centered}>
      <Text style={styles.error}>Tutorial not found</Text>
      <Pressable onPress={() => router.back()} style={{ marginTop: 20 }}>
        <Text style={{ color: theme.colors.primary }}>Go Back</Text>
      </Pressable>
    </View>
  );

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()}>
          <Text style={styles.backButton}>← Back</Text>
        </Pressable>
        <Text style={styles.headerTitle} numberOfLines={1}>{tutorial.title}</Text>
      </View>

      {/* Video Player Section */}
      <View style={styles.videoContainer}>
        <Video
          source={{ uri: tutorial.videoUrl || 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
          style={styles.video}
          useNativeControls
          resizeMode={ResizeMode.CONTAIN}
        />
      </View>

      {/* Tabs to switch between Video Timeline and Text Guide */}
      <View style={styles.tabBar}>
        <Pressable 
            style={[styles.tab, activeTab === 'timeline' && styles.activeTab]} 
            onPress={() => setActiveTab('timeline')}
        >
          <Text style={[styles.tabText, activeTab === 'timeline' && styles.activeTabText]}>Video Timeline</Text>
        </Pressable>
        <Pressable 
            style={[styles.tab, activeTab === 'manual' && styles.activeTab]} 
            onPress={() => setActiveTab('manual')}
        >
          <Text style={[styles.tabText, activeTab === 'manual' && styles.activeTabText]}>Tutorial Guide 📄</Text>
        </Pressable>
      </View>

      <ScrollView style={styles.content}>
        {activeTab === 'timeline' ? (
          <View>
            {/* Visual progress tracker */}
            <View style={styles.progressSection}>
                <ProgressBar 
                    progress={tutorial.timelinedAudioTranscript.length > 0 
                        ? ((activeStepIndex + 1) / tutorial.timelinedAudioTranscript.length) * 100 
                        : 0}
                    title={tutorial.timelinedAudioTranscript[activeStepIndex]?.text || "Introduction"}
                />
            </View>

            {/* List of timestamped tutorial steps */}
            <View style={styles.stepsList}>
                {tutorial.timelinedAudioTranscript.map((item, index) => (
                    <StepItem 
                        key={index}
                        time={`${Math.floor(item.timestamp / 60)}:${Math.floor(item.timestamp % 60).toString().padStart(2, '0')}`}
                        title={`Step ${item.order}`}
                        description={item.text}
                        active={index === activeStepIndex}
                        onPress={() => setActiveStepIndex(index)}
                    />
                ))}
            </View>
          </View>
        ) : (
          /* AI-generated text instruction section */
          <View style={styles.manualContainer}>
            <View style={styles.aiBadge}>
                <Text style={styles.aiBadgeText}>GENERATED BY AI FROM VIDEO</Text>
            </View>
            <View style={styles.manualCard}>
                <Text style={styles.manualTitle}>Full Tutorial Instructions</Text>
                <Text style={styles.manualContent}>{tutorial.structuredInstructions}</Text>
            </View>
          </View>
        )}
      </ScrollView>

      <Pressable style={styles.fab} onPress={() => router.push("/record")}>
        <Text style={styles.fabText}>+</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#121212' },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#121212' },
  error: { color: 'white', textAlign: 'center' },
  header: { padding: 20, paddingTop: 60, backgroundColor: '#000', flexDirection: 'row', alignItems: 'center' },
  backButton: { color: '#fff', fontSize: 16, marginRight: 15 },
  headerTitle: { color: theme.colors.accentGold, fontSize: 16, fontWeight: 'bold', flex: 1 },
  videoContainer: { width: '100%', height: 230, backgroundColor: '#000' },
  video: { width: '100%', height: '100%' },
  tabBar: { flexDirection: 'row', backgroundColor: theme.colors.card, borderBottomWidth: 1, borderBottomColor: '#333' },
  tab: { flex: 1, padding: 15, alignItems: 'center', borderBottomWidth: 3, borderBottomColor: 'transparent' },
  activeTab: { borderBottomColor: theme.colors.primary },
  tabText: { color: theme.colors.textSecondary, fontWeight: 'bold' },
  activeTabText: { color: theme.colors.primary },
  content: { flex: 1 },
  progressSection: { padding: 20, backgroundColor: theme.colors.card, marginBottom: 10 },
  stepsList: { padding: 20 },
  manualContainer: { padding: 20 },
  aiBadge: { alignSelf: 'flex-start', backgroundColor: '#333', padding: 6, borderRadius: 4, marginBottom: 15, borderWidth: 1, borderColor: theme.colors.primary },
  aiBadgeText: { color: theme.colors.primary, fontSize: 10, fontWeight: 'bold' },
  manualCard: { backgroundColor: theme.colors.card, padding: 20, borderRadius: 12 },
  manualTitle: { color: theme.colors.accentGold, fontSize: 16, fontWeight: 'bold', marginBottom: 10 },
  manualContent: { color: '#ddd', lineHeight: 22, fontSize: 14 },
  fab: {
    position: "absolute", right: 24, bottom: 24, width: 60, height: 60, borderRadius: 30,
    backgroundColor: theme.colors.primary, alignItems: "center", justifyContent: "center",
    elevation: 8, shadowColor: "#000", shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 4,
  },
  fabText: { color: "#fff", fontSize: 32, fontWeight: '300' },
});