import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';
import { TutorialProcessingStatus } from '../jobs/tutorial-status';

export type TutorialDocument = HydratedDocument<Tutorial>;

@Schema({
  timestamps: { createdAt: true, updatedAt: true },
  collection: 'tutorials',
})
export class Tutorial {
  /**
   * Reference to the uploaded video stored in GridFS
   */
  @Prop({ type: Types.ObjectId, required: true })
  videoGridFsFileId: Types.ObjectId;

  /**
   * Unique filename used when storing video in GridFS
   */
  @Prop({ type: String })
  videoFileName?: string;

  /**
   * Generated by LLM from transcript
   */
  @Prop({ type: String })
  title?: string;

  /**
   * Generated by LLM from transcript
   */
  @Prop({ type: String })
  shortDescription?: string;

  /**
   * If the video is later hosted remotely (e.g. CDN, S3)
   */
  @Prop({ type: String })
  videoUrl?: string;

  /**
   * If the video is later stored on local disk
   */
  @Prop({ type: String })
  videoLocalFilePath?: string;

  /**
   * Generated by speech-to-text job
   */
  @Prop({ type: String })
  audioTranscript?: string;

  /**
   * Speech-to-text with timestamps
   */
  @Prop({
    type: [
      {
        order: { type: Number, required: true },
        timestamp: { type: Number, required: true },
        text: { type: String, required: true },
      },
    ],
    default: undefined, // important to avoid empty array before processing
  })
  timelinedAudioTranscript?: {
    order: number;
    timestamp: number;
    text: string;
  }[];

  /**
   * Generated by LLM from transcript
   */
  @Prop({ type: String })
  structuredInstructions?: string;

  @Prop({ type: String })
  vectorStoreFileId?: string;

  /**
   * Processing lifecycle state
   * examples:
   * - uploaded
   * - transcribing
   * - transcript_ready
   * - llm_processing
   * - completed
   * - failed
   */
  @Prop({
    type: String,
    required: true,
    default: 'uploaded',
    index: true,
  })
  processingStatus: TutorialProcessingStatus;

  @Prop({ type: Number, default: 0 })
  processingAttempts?: number;

  /**
   * createdAt is automatically added by timestamps
   */
  createdAt: Date;

  updatedAt: Date;
}

export const TutorialSchema = SchemaFactory.createForClass(Tutorial);
